controller_manager_ns: moveit_simple_controller_manager
controller_list:
  - name: left_arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [LTorsoJoint, LShoulderJoint, LArmJoint, LArmElbowJoint, LForearmYawJoint, LForearmRollJoint, LHandPitchJoint]
  - name: right_arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [RTorsoJoint, RShoulderJoint, RArmJoint, RArmElbowJoint, RForearmYawJoint, RForearmRollJoint, RHandPitchJoint]
