#!/bin/bash

# Check if expclient is running
# -x flag only match processes whose name (or command line if -f is specified) exactly match the pattern. 

if pgrep -x "expclient" > /dev/null
then
    echo "expclient OK"
else
    echo "expclient is off - REBOOT"
    #shutdown -r now
    systemctl reboot -i
fi
