#!/bin/bash

t=1
while [ $t -le 150 ]
do
    echo "startup delay, $t / 150 sec"
    sleep 1
    t=$(( $t + 1 ))
done

f=1
while [ 1 ]; do
   ping -c 1 192.168.101.1

    if [ $? -eq 0 ]
    then
       echo "wlan0 active"
       sleep 5
       f=1
    else
       echo "wlan0 failed $f times / 10"
       f=$(( $f + 1 ))
       if [ $f -eq 11 ]
       then
           echo "stop and reboot now!"
           reboot
       fi
       sleep 1
    fi
done
