#!/bin/bash

t=1
while [ $t -le 150 ]
do
    echo "startup delay, $t / 150 sec"
    sleep 1
    t=$(( $t + 1 ))
done

while [ 1 ]; do
   ping -c 1 192.168.101.1

    if [ $? -eq 0 ]
    then
       echo "wlan0 active"
    else
       echo "wlan0 failed"
       echo "stop and reboot now!"
       reboot
    fi

    sleep 5
done
