#!/bin/bash
DISPLAY=:0 chromium-browser --start-maximized "https://translate.google.com/#ru/en" &
sleep 10

DISPLAY=:0 xdotool mousemove 58 418 click 1
sleep 5

timeCnt=0

while [ 1 ]; do
#  DISPLAY=:0 xdotool getmouselocation
#  ((timeCnt++))
#  echo "timeCnt=$timeCnt"
#  if [ "$timeCnt" -eq 60 ]; then
#    DISPLAY=:0 xdotool mousemove 493 318 click 1
#    sleep 1
#    DISPLAY=:0 xdotool mousemove 58 418 click 1
#    timeCnt=0
#  fi

  #select text
  DISPLAY=:0 xdotool mousemove x238 y356 click 1
  DISPLAY=:0 xdotool key --delay 0 --clearmodifiers ctrl+a
  DISPLAY=:0 xdotool key --delay 0 --clearmodifiers ctrl+c

  googleResult="$(DISPLAY=:0 xclip -o)"

  echo "RESULT:$googleResult"

  if [ "$googleResult" == "" ]; then
   echo "NO RESULT" 
  fi

  DISPLAY=:0 xclip -i /dev/null
  googleResult=""

  #stop mic capture
  DISPLAY=:0 xdotool mousemove 72 418 click 1
  sleep 1

  #clear text
  DISPLAY=:0 xdotool mousemove 493 318 click 1
  sleep 1

  #restore mic capture
  DISPLAY=:0 xdotool mousemove 58 418 click 1

  sleep 5

done
